version: "3"
services:
  nestjs-server:
    container_name: smartcine-nestjs-server
    restart: on-failure:3
    networks:
      - smartcine-network
    build:
      context: . # use the current directory as the build contexts
      dockerfile: Dockerfile
    ports:
      - ${PORT}:${PORT}
    environment:
      - PORT=${PORT}
      - DATABASE_URL=${DATABASE_URL}
      - SALT=${SALT}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_SECRET=${REDIS_SECRET}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_REFRESH_SECRET=${JWT_REFRESH_SECRET}
      - JWT_EXPIRES_IN=${JWT_EXPIRES_IN}
      - VNPAY_URL=${VNPAY_URL}
      - VNPAY_VERSION=${VNPAY_VERSION}
      - VNPAY_CURRCODE=${VNPAY_CURRCODE}

networks:
  smartcine-network:
    external: true
